# Volume variable is used in my mac dont forget to replace!

version: "3.0"
services:
  db:
      image: mysql:latest
      container_name: airflow_db_v4
      env_file: ./env_mysql_db
      ports:
        - 3306:3306
      volumes:
        - /Users/mragungsetiaji/Documents/dags/mysql:/var/lib/mysql
      command: ["mysqld","--default-authentication-plugin=mysql_native_password"]


